### ISSUE TITLE
k8s 报错收集

### ISSUE THREAD

**Issue by vislee** [vislee/leevis.com#186]
### 错误

kubectl create -f dapi-volume-resources.yaml
`Error from server (BadRequest): error when creating "dapi-volume-resources.yaml": Pod in version "v1" cannot be handled as a Pod: unable to parse quantity's suffix`

可能原因 ： yaml文件资源val拼写错误
例如：

```yaml
      resources:
        requests:
          memory: "32MMi"    //    <---------- 此处多写了一个M
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"
```

### 总结
